name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build docker image
      run: make package
    - name: Upload image
      env: 
        super_secret: DOCKER_TOKEN
      run: make upload
