name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and upload image
      env:
        DOCKER_USERNAME: hsmade
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
      run: make upload
